name: pull request
on:
  pull_request:
    branches:
      - master
      - main

jobs:
  shared-operator-workflow:
    name: shared-operator-workflow
    uses: redhat-cop/github-workflows-operators/.github/workflows/pr-operator.yml@v1.0.0
    with:
      BUILD_PLATFORMS: "linux/amd64,linux/arm64,linux/ppc64le"
