name: push
on:
  push:
    branches:
      - main
      - master
    tags:
      - v*

jobs:
  shared-operator-workflow:
    name: shared-operator-workflow
    uses: redhat-cop/github-workflows-operators/.github/workflows/release-operator.yml@v1.0.0
    secrets:
      COMMUNITY_OPERATOR_PAT: ${{ secrets.COMMUNITY_OPERATOR_PAT }}
      BUNDLE_IMAGE_REPOSITORY: ${{ secrets.BUNDLE_IMAGE_REPOSITORY }}
      OPERATOR_IMAGE_REPOSITORY: ${{ secrets.OPERATOR_IMAGE_REPOSITORY }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
    with:
      BUILD_PLATFORMS: "linux/amd64,linux/arm64,linux/ppc64le"
      PR_ACTOR: "raffaele.spazzoli@gmail.com"
